3-GET-/api/categories implementation TDD and error handling
Oliver1334/nc-games-beproject pull request #2
Opened 2023-02-20 16:09 UTC by Oliver1334

2023-02-20 16:36 UTC, Beth-McCormack commented on __tests__/app.test.js
> +                        console.log(res.body)
Make sure to remove console.logs and comments before committing :)

2023-02-20 16:38 UTC, Beth-McCormack commented on __tests__/app.test.js
> +          ];
Make your test more dynamic, dont hard code values. Think of other ways you can test your result.

2023-02-20 16:39 UTC, Beth-McCormack requested changes
see comments

2023-02-21 10:58 UTC, yalicee approved these changes
Looks really good Oliver!

2023-02-21 10:58 UTC, yalicee commented on __tests__/app.test.js
> +            // owner
delete all comented out code

2023-02-21 16:21 UTC, merged